apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/Relay24/sample-devops-infra.git'
              revision: HEAD
              directories:
                - path: apps-config/helm-apps/*  # !!! apps-config/
                  metadata:
                    labels:
                      app-type: helm
                - path: apps-config/yaml-apps/*  # !!! apps-config/
                  metadata:
                    labels:
                      app-type: yaml
          - git:
              repoURL: 'https://github.com/Relay24/sample-devops-infra.git'
              revision: HEAD
              files:
                - path: "apps-config/external-apps/*.yaml"

  template:
    metadata:
      name: '{{appName | default(path.basename)}}'
      labels:
        app-type: '{{appType | default(path.basename)}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: '{{path}}'
        helm:
          valueFiles:
            - '{{helmValuesFile | default("")}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{appNamespace | default(path.basename)}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true