apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Relay24/sample-devops-infra.git'
        revision: HEAD
        directories:
          - path: apps-config/helm-apps/*
            metadata:
              labels:
                app-type: helm
          - path: apps-config/yaml-apps/*
            metadata:
              labels:
                app-type: yaml

  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        app-type: '{{appType}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true